module.exports = (serquelize, DataTypes) => {
	const Dog = serquelize.define('Dog', {
		dog_number:{
			type: DataTypes.INTEGER,
			unique: true,
			primaryKey: true
		},
		dog_name: DataTypes.STRING,
		status: DataTypes.STRING,
		link_to_Archive: DataTypes.STRING,
		insurance: DataTypes.STRING,
		chip_no: DataTypes.STRING,
		dkk_no: DataTypes.STRING,	
		born: DataTypes.STRING,
		kennel_name: DataTypes.STRING,
		gender: DataTypes.STRING,
		colour: DataTypes.STRING,
		race: DataTypes.STRING,
		buy_status: DataTypes.STRING,
		training_start: DataTypes.STRING,
		approval_date: DataTypes.STRING,
		initials: DataTypes.STRING,
		instructor: DataTypes.STRING,
		user: DataTypes.STRING,
		outplacement: DataTypes.STRING,
		follow_up: DataTypes.STRING,
		grant_date: DataTypes.STRING,
		invoice_price: DataTypes.STRING,
		invoice_municipality: DataTypes.STRING,
		owner_certificate: DataTypes.STRING,
		pedigree: DataTypes.STRING,
		reg_attest: DataTypes.STRING,
		added_agria: DataTypes.STRING,
		healtcard_send: DataTypes.STRING,
		removed_agria: DataTypes.STRING,
		removed_DKK: DataTypes.STRING,
		removed_dog_reg: DataTypes.STRING,
		account_no: DataTypes.STRING,
		removed_cause: DataTypes.STRING,
		remark: DataTypes.TEXT,
		status_changes: DataTypes.STRING,
		walk_speed: DataTypes.STRING,
		temper: DataTypes.STRING,
		buying_price: DataTypes.STRING,
		buying_date: DataTypes.STRING,
		feedhost_pickup_date: DataTypes.STRING,
		municipality: DataTypes.STRING,
		feedhost_history: DataTypes.STRING
	})
	return Dog
}