module.exports = (serquelize, DataTypes) => {
  const Instructor = serquelize.define("Instructor", {
    instructor_name: DataTypes.STRING,
	instructor_salaryNo: DataTypes.STRING,

    feedhost_adress: DataTypes.STRING,
	feedhost_name: DataTypes.STRING,
    feedhost_zip: DataTypes.STRING,
    feedhost_city: DataTypes.STRING,
    dog_number: DataTypes.STRING,
    dog_name: DataTypes.STRING,
    dog_race: DataTypes.STRING,
    dog_colour: DataTypes.STRING,
    dog_gender: DataTypes.STRING,
    dog_birth: DataTypes.STRING,
    dog_chipNo: DataTypes.STRING,
    honorarfeedhost_without: DataTypes.STRING,
    honorarfeedhost_with: DataTypes.STRING,
    numberkilom_without: DataTypes.STRING,
    numberkilom_with: DataTypes.STRING,
    otherexpenses: DataTypes.STRING,
    otherexpenses_without: DataTypes.STRING,
    otherexpenses_with: DataTypes.STRING,
    diverseexpenses: DataTypes.STRING,
    diverseexpenses_without: DataTypes.STRING,
    diverseexpenses_with: DataTypes.STRING,
    numberdays: DataTypes.STRING,
    numberdays_without: DataTypes.STRING,
    numberdays_with: DataTypes.STRING,
    from: DataTypes.STRING,
    to: DataTypes.STRING,
    driving_drivingtime_sum: DataTypes.STRING,
    driving_drivingkm_sum: DataTypes.STRING,
    visit_report_date: DataTypes.STRING,
    visit_report_environment: DataTypes.STRING,
    visit_report_finished_work: DataTypes.STRING,
    visit_report_options_challenges: DataTypes.STRING,
    visit_report_next_work: DataTypes.STRING,
    monthly_report_problem1: DataTypes.STRING,
    monthly_report_problem2: DataTypes.STRING,
    monthly_report_problem3: DataTypes.STRING,
    monthly_report_problem4: DataTypes.STRING,
  });
  return Instructor;
};